service: ${env:STACK_NAME}
frameworkVersion: "3.x"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
  hello:
    handler: handler.hello

serverlessCloudformationStackManager:
  useChangeSets: true
  changeSetName: ${env:CHANGE_SET_NAME, ''}

plugins:
  - ./../../dist
